import React, { useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Dimensions,
  Image,
  Linking,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import MapView, { Marker, Overlay, PROVIDER_DEFAULT } from "react-native-maps";
import { Picker } from "@react-native-picker/picker";
import { Ionicons } from "@expo/vector-icons";

// ============================================================
// NEERAKSH MOBILE WORKING PROTOTYPE
// ============================================================
// Mirrors the workflow shown in the SIH PPT:
//
// Sign In
//   -> Select Dam
//   -> Dam Details
//   -> Simulation / Scenario Generation
//   -> Flood Inundation Map
//   -> HLL / SPH / Delft3D comparison
//   -> Impact Analysis
//   -> GIS export
//
// No fabricated simulation values are displayed.
// HLL uses the completed Mettur output already generated by
// C:\NEERAKSH-1\simulations\outputs\mettur\hll_test
// ============================================================

// For a physical phone using Expo Go:
// replace with your Windows PC IPv4 address, e.g.
// http://192.168.1.5:8000
//
// Android emulator:
// http://10.0.2.2:8000
//
// iOS simulator:
// http://127.0.0.1:8000
const API_BASE_URL = "http://192.168.21.210:8000";

const DAM_COORD = {
  latitude: 11.8030556,
  longitude: 77.8066667,
};

type Screen =
  | "login"
  | "dashboard"
  | "dam"
  | "scenario"
  | "simulation"
  | "map"
  | "impact"
  | "export";

type Dam = {
  name: string;
  river: string;
  district: string;
  state: string;
  latitude: number;
  longitude: number;
  height_m: number | null;
  frl_m: number | null;
  mwl_m: number | null;
  gross_storage_mcm: number | null;
  pic?: string | null;
  reservoir?: string | null;
  source?: string | null;
  observed: {
    status: string;
    current_level_ft?: number;
    current_storage_mcft?: number;
    inflow_cusecs?: number;
    outflow_cusecs?: number;
    retrieved_at?: string;
    observed_at?: string;
    note?: string;
  };
};

type Scenario = {
  id: string;
  width_m: number | null;
  formation_time_hr: number | null;
  simulation_allowed: boolean;
  breach_location_verified: boolean;
  status: string;
};

type Results = {
  model: string;
  scenario: string;
  hypothetical: boolean;
  validated_forecast: boolean;
  derived: {
    flooded_area_km2: number | null;
    wet_cells: number | null;
    max_depth_m: number | null;
    max_velocity_mps: number | null;
  };
  comparison: {
    hll: string;
    sph: string;
    delft3d: string;
  };
};

type LayerName = "max-depth" | "max-velocity" | "arrival-time";

type LayerMeta = {
  url: string;
  bounds: [[number, number], [number, number]];
  min: number | null;
  max: number | null;
};

function fmt(v: any, digits = 2) {
  if (v === null || v === undefined || Number.isNaN(Number(v))) return "—";
  return Number(v).toFixed(digits);
}

async function getJson(url: string) {
  const response = await fetch(url);
  const text = await response.text();
  let data: any = null;

  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    throw new Error(`Invalid JSON response from ${url}`);
  }

  if (!response.ok) {
    const detail =
      typeof data?.detail === "string"
        ? data.detail
        : data?.message || `HTTP ${response.status}`;
    throw new Error(detail);
  }

  return data;
}

function normalizeDamPayload(damResponse: any, liveResponse: any): Dam | null {
  const raw = damResponse?.dam ?? damResponse;
  if (!raw || typeof raw !== "object") return null;

  const observed = liveResponse?.status
    ? liveResponse
    : raw.observed ?? {};

  return {
    name: raw.name ?? raw.dm_name ?? "Mettur Dam",
    river: raw.river ?? raw.main_river ?? "Cauvery",
    district: raw.district ?? "Salem",
    state: raw.state ?? "Tamil Nadu",
    latitude: Number(raw.latitude ?? raw.lat ?? DAM_COORD.latitude),
    longitude: Number(raw.longitude ?? raw.lon ?? DAM_COORD.longitude),
    height_m: raw.height_m != null ? Number(raw.height_m) : null,
    frl_m: raw.frl_m != null ? Number(raw.frl_m) : null,
    mwl_m: raw.mwl_m != null ? Number(raw.mwl_m) : null,
    gross_storage_mcm:
      raw.gross_storage_mcm != null
        ? Number(raw.gross_storage_mcm)
        : raw.gs_st_cap != null
          ? Number(raw.gs_st_cap)
          : null,
    pic: raw.pic ?? raw.PIC ?? null,
    reservoir: raw.reservoir ?? "Stanley Reservoir",
    source: raw.source ?? null,
    observed: {
      status: observed.status ?? "LIVE_DATA_UNAVAILABLE",
      current_level_ft:
        observed.current_level_ft != null
          ? Number(observed.current_level_ft)
          : undefined,
      current_storage_mcft:
        observed.current_storage_mcft != null
          ? Number(observed.current_storage_mcft)
          : undefined,
      inflow_cusecs:
        observed.inflow_cusecs != null
          ? Number(observed.inflow_cusecs)
          : undefined,
      outflow_cusecs:
        observed.outflow_cusecs != null
          ? Number(observed.outflow_cusecs)
          : undefined,
      retrieved_at: observed.timestamp ?? observed.retrieved_at,
      observed_at: observed.observed_at,
      note: observed.note ?? observed.message,
    },
  };
}

export default function App() {
  const [screen, setScreen] = useState<Screen>("login");
  const [dam, setDam] = useState<Dam | null>(null);
  const [scenarios, setScenarios] = useState<Scenario[]>([]);
  const [scenarioId, setScenarioId] = useState("METTUR_SCREENING_BASE");
  const [results, setResults] = useState<Results | null>(null);
  const [layer, setLayer] = useState<LayerName>("max-depth");
  const [layerMeta, setLayerMeta] = useState<LayerMeta | null>(null);
  const [loading, setLoading] = useState(false);
  const [apiError, setApiError] = useState("");

  useEffect(() => {
    Promise.all([
      getJson(`${API_BASE_URL}/api/dam/mettur`),
      getJson(`${API_BASE_URL}/api/reservoir/mettur`),
      getJson(`${API_BASE_URL}/api/scenarios/mettur`),
    ])
      .then(([damResponse, liveResponse, scenarioResponse]) => {
        const normalizedDam = normalizeDamPayload(damResponse, liveResponse);

        if (!normalizedDam) {
          throw new Error("Mettur dam record is unavailable from the backend.");
        }

        setDam(normalizedDam);
        setScenarios(
          Array.isArray(scenarioResponse?.scenarios)
            ? scenarioResponse.scenarios
            : []
        );
        setApiError("");
      })
      .catch((error: any) => {
        setApiError(
          error?.message ||
            "Backend unavailable. Start the NEERAKSH FastAPI server and check API_BASE_URL."
        );
      });
  }, []);

  async function openSimulation(target: "simulation" | "map" = "simulation") {
    if (scenarioId !== "METTUR_SCREENING_BASE") {
      Alert.alert(
        "No completed output",
        "NEERAKSH will not generate a result for a scenario that has not actually been simulated."
      );
      return;
    }

    setLoading(true);
    try {
      const data = await getJson(`${API_BASE_URL}/api/results/mettur`);
      setResults(data);
      setScreen(target);
    } catch (e: any) {
      Alert.alert("Simulation result unavailable", e?.message || "Could not load result.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    if (!results) return;
    getJson(`${API_BASE_URL}/api/layer/${layer}/metadata`)
      .then(setLayerMeta)
      .catch(() => setLayerMeta(null));
  }, [results, layer]);

  const selectedScenario = useMemo(
    () => scenarios.find(s => s.id === scenarioId),
    [scenarios, scenarioId]
  );

  function reset() {
    setScreen("dashboard");
    setResults(null);
    setLayerMeta(null);
  }

  if (screen === "login") {
    return <LoginScreen onContinue={() => setScreen("dashboard")} error={apiError} />;
  }

  return (
    <SafeAreaView style={styles.safe}>
      <StatusBar barStyle="dark-content" />
      <Header onHome={() => setScreen("dashboard")} />

      {screen === "dashboard" && (
        <DashboardScreen
          dam={dam}
          onDam={() => setScreen("dam")}
          onScenario={() => setScreen("scenario")}
          onSimulation={() => openSimulation("simulation")}
          onMap={() => openSimulation("map")}
          onImpact={() => setScreen(results ? "impact" : "scenario")}
          onExport={() => setScreen("export")}
        />
      )}

      {screen === "dam" && (
        <DamScreen
          dam={dam}
          onBack={() => setScreen("dashboard")}
          onNext={() => setScreen("scenario")}
        />
      )}

      {screen === "scenario" && (
        <ScenarioScreen
          scenarios={scenarios}
          selected={scenarioId}
          setSelected={setScenarioId}
          selectedScenario={selectedScenario}
          onBack={() => setScreen("dam")}
          onRun={openSimulation}
          loading={loading}
        />
      )}

      {screen === "simulation" && (
        <SimulationScreen
          results={results}
          scenario={selectedScenario}
          onBack={() => setScreen("scenario")}
          onMap={() => setScreen("map")}
          onImpact={() => setScreen("impact")}
        />
      )}

      {screen === "map" && (
        <FloodMapScreen
          results={results}
          layer={layer}
          setLayer={setLayer}
          layerMeta={layerMeta}
          onBack={() => setScreen("simulation")}
          dam={dam}
        />
      )}

      {screen === "impact" && (
        <ImpactScreen
          results={results}
          onBack={() => setScreen(results ? "simulation" : "dashboard")}
        />
      )}

      {screen === "export" && (
        <ExportScreen onBack={() => setScreen("dashboard")} />
      )}
    </SafeAreaView>
  );
}

function Header({ onHome }: { onHome: () => void }) {
  return (
    <View style={styles.header}>
      <TouchableOpacity onPress={onHome} style={styles.headerIcon}>
        <Ionicons name="water-outline" size={24} color="#123B58" />
      </TouchableOpacity>
      <View>
        <Text style={styles.headerBrand}>NEERAKSH</Text>
        <Text style={styles.headerSub}>Flood Intelligence</Text>
      </View>
      <View style={styles.headerStatus}>
        <View style={styles.statusDot} />
        <Text style={styles.headerStatusText}>PROTOTYPE</Text>
      </View>
    </View>
  );
}

function LoginScreen({ onContinue, error }: { onContinue: () => void; error: string }) {
  return (
    <SafeAreaView style={styles.safe}>
      <StatusBar barStyle="dark-content" />
      <View style={styles.login}>
        <View style={styles.logoCircle}>
          <Ionicons name="water" size={52} color="#fff" />
        </View>
        <Text style={styles.logoText}>NEERAKSH</Text>
        <Text style={styles.loginTitle}>Flood Simulation & Impact Intelligence</Text>
        <Text style={styles.loginText}>
          A working prototype for dam-break scenario simulation, inundation mapping and impact analysis.
        </Text>

        {error ? <View style={styles.apiWarning}><Text style={styles.apiWarningText}>{error}</Text></View> : null}

        <TouchableOpacity style={styles.primaryButton} onPress={onContinue}>
          <Text style={styles.primaryButtonText}>CONTINUE TO DASHBOARD</Text>
          <Ionicons name="arrow-forward" size={18} color="#fff" />
        </TouchableOpacity>

        <Text style={styles.sourceNote}>
          Prototype displays only official observations and completed model outputs.
        </Text>
      </View>
    </SafeAreaView>
  );
}

function DashboardScreen(props: any) {
  const {
    dam,
    onDam,
    onScenario,
    onSimulation,
    onMap,
    onImpact,
    onComparison,
    onExport,
  } = props;
  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <View style={styles.hero}>
        <Text style={styles.eyebrow}>GIS DECISION SUPPORT DASHBOARD</Text>
        <Text style={styles.heroTitle}>Dam-break flood intelligence</Text>
        <Text style={styles.heroText}>
          Simulate a defined scenario, visualize inundation and inspect model outputs.
        </Text>
      </View>

      <SectionTitle title="SELECT DAM" />
      <TouchableOpacity style={styles.damCard} onPress={onDam}>
        <View style={styles.damIcon}><Ionicons name="business-outline" size={28} color="#138A52" /></View>
        <View style={{ flex: 1 }}>
          <Text style={styles.cardTitle}>{dam?.name || "Mettur Dam"}</Text>
          <Text style={styles.cardSub}>{dam?.river || "Cauvery"} River · {dam?.district || "Salem"}</Text>
          <Text style={styles.cardSub}>{dam?.state || "Tamil Nadu"}</Text>
        </View>
        <Ionicons name="chevron-forward" size={21} color="#7C8994" />
      </TouchableOpacity>

      <SectionTitle title="WORKFLOW" />
      <View style={styles.workflowGrid}>
        <WorkflowButton icon="water-outline" title="Dam Details" onPress={onDam} />
        <WorkflowButton icon="options-outline" title="Scenario Generation" onPress={onScenario} />
        <WorkflowButton icon="pulse-outline" title="Simulation Result" onPress={onSimulation} />
        <WorkflowButton icon="map-outline" title="Flood Map" onPress={onMap} />
        <WorkflowButton icon="analytics-outline" title="Impact Analysis" onPress={onImpact} />
        <WorkflowButton icon="download-outline" title="GIS Export" onPress={onExport} />
        <WorkflowButton icon="radio-outline" title="Observation" onPress={onDam} />
      </View>

      <View style={styles.notice}>
        <Ionicons name="information-circle-outline" size={20} color="#8A6410" />
        <Text style={styles.noticeText}>
          Scenario: METTUR_SCREENING_BASE · 2D HLL screening output
        </Text>
      </View>
    </ScrollView>
  );
}

function DamScreen({ dam, onBack, onNext }: any) {
  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <BackButton onPress={onBack} />
      <ScreenTitle title="DAM DETAILS" subtitle="Official Mettur reference and current observation" />

      <View style={styles.largeCard}>
        <Text style={styles.bigTitle}>{dam?.name || "Mettur Dam"}</Text>
        <Text style={styles.cardSub}>
          {dam?.river || "Cauvery"} River · {dam?.district || "Salem"}, Tamil Nadu
        </Text>
        <Text style={styles.cardSub}>
          {dam?.reservoir || "Stanley Reservoir"} · Official dam record
        </Text>
        <View style={styles.mapMini}>
          <MapView
            provider={PROVIDER_DEFAULT}
            style={{ flex: 1 }}
            initialRegion={{
              latitude: Number(dam?.latitude ?? DAM_COORD.latitude),
              longitude: Number(dam?.longitude ?? DAM_COORD.longitude),
              latitudeDelta: 0.12,
              longitudeDelta: 0.12,
            }}
            scrollEnabled={false}
            zoomEnabled={false}
          >
            <Marker coordinate={DAM_COORD} title="Mettur Dam" />
          </MapView>
        </View>
        <View style={styles.metricGrid}>
          <Metric label="Dam height" value={`${fmt(dam?.height_m)} m`} />
          <Metric label="FRL" value={`${fmt(dam?.frl_m)} m`} />
          <Metric label="MWL" value={`${fmt(dam?.mwl_m)} m`} />
          <Metric label="Gross storage" value={`${fmt(dam?.gross_storage_mcm)} MCM`} />
        </View>
      </View>

      <SectionTitle title="LIVE RESERVOIR OBSERVATION" />
      <View style={styles.largeCard}>
        <View style={styles.liveBadge}>
          <View style={styles.statusDot} />
          <Text style={styles.liveBadgeText}>
            {dam?.observed?.status === "LIVE_GOVERNMENT_DATA" ? "LIVE GOVERNMENT DATA" : "STORED OFFICIAL SNAPSHOT"}
          </Text>
        </View>
        <View style={styles.metricGrid}>
          <Metric label="Current level" value={`${fmt(dam?.observed?.current_level_ft)} ft`} />
          <Metric label="Storage" value={`${fmt(dam?.observed?.current_storage_mcft, 0)} M.Cft`} />
          <Metric label="Inflow" value={`${fmt(dam?.observed?.inflow_cusecs, 0)} cusecs`} />
          <Metric label="Outflow" value={`${fmt(dam?.observed?.outflow_cusecs, 0)} cusecs`} />
        </View>
        <Text style={styles.timestamp}>
          {dam?.observed?.retrieved_at || dam?.observed?.observed_at || "Timestamp unavailable"}
        </Text>
        <Text style={styles.sourceNoteSmall}>
          Source: Tamil Nadu Agriculture Reservoir Portal
        </Text>
      </View>

      <TouchableOpacity style={styles.primaryButton} onPress={onNext}>
        <Text style={styles.primaryButtonText}>CONTINUE TO SCENARIO</Text>
        <Ionicons name="arrow-forward" size={18} color="#fff" />
      </TouchableOpacity>
    </ScrollView>
  );
}

function ScenarioScreen({ scenarios, selected, setSelected, selectedScenario, onBack, onRun, loading }: any) {
  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <BackButton onPress={onBack} />
      <ScreenTitle title="SCENARIO GENERATION" subtitle="Select a defined screening scenario" />

      <View style={styles.largeCard}>
        <Text style={styles.label}>Mettur dam-break screening scenario</Text>
        <View style={styles.pickerWrap}>
          <Picker selectedValue={selected} onValueChange={setSelected}>
            {scenarios.map((s: Scenario) => (
              <Picker.Item key={s.id} label={s.id} value={s.id} />
            ))}
          </Picker>
        </View>

        {selectedScenario && (
          <>
            <View style={styles.metricGrid}>
              <Metric label="Screening width" value={`${fmt(selectedScenario.width_m)} m`} />
              <Metric label="Formation time" value={`${fmt(selectedScenario.formation_time_hr)} hr`} />
            </View>
            <View style={styles.notice}>
              <Ionicons name="warning-outline" size={20} color="#8A6410" />
              <Text style={styles.noticeText}>
                Screening parameters only. Breach location and actual failure geometry are not verified.
              </Text>
            </View>
          </>
        )}
      </View>

      <View style={styles.largeCard}>
        <Text style={styles.cardTitle}>Simulation policy</Text>
        <Text style={styles.bodyText}>
          NEERAKSH shows an output only when a corresponding model run exists. Unsimulated scenarios are not assigned predicted flood values.
        </Text>
      </View>

      <TouchableOpacity
        style={[styles.primaryButton, selected !== "METTUR_SCREENING_BASE" && styles.disabledButton]}
        onPress={onRun}
        disabled={loading}
      >
        {loading ? <ActivityIndicator color="#fff" /> : (
          <>
            <Text style={styles.primaryButtonText}>
              {selected === "METTUR_SCREENING_BASE" ? "VIEW COMPLETED HLL RESULT" : "NO COMPLETED RESULT"}
            </Text>
            <Ionicons name="play" size={18} color="#fff" />
          </>
        )}
      </TouchableOpacity>
    </ScrollView>
  );
}

function SimulationScreen({ results, scenario, onBack, onMap, onImpact }: any) {
  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <BackButton onPress={onBack} />
      <ScreenTitle title="SIMULATION RESULT" subtitle="Completed Mettur HLL run" />

      {!results ? (
        <View style={styles.largeCard}>
          <Text style={styles.bodyText}>
            No completed simulation result is loaded. Use Scenario Generation and select the completed BASE scenario.
          </Text>
        </View>
      ) : (
        <>
          <View style={styles.resultBanner}>
            <View style={styles.resultCheck}><Ionicons name="checkmark" size={26} color="#fff" /></View>
            <View style={{ flex: 1 }}>
              <Text style={styles.cardTitle}>Simulation output available</Text>
              <Text style={styles.cardSub}>
                {results.model} · {typeof scenario === "string" ? scenario : scenario?.id || "METTUR_SCREENING_BASE"}
              </Text>
            </View>
          </View>

          <View style={styles.resultGrid}>
            <ResultCard title="Max depth" value={`${fmt(results.derived.max_depth_m)} m`} />
            <ResultCard title="Max velocity" value={`${fmt(results.derived.max_velocity_mps)} m/s`} />
            <ResultCard title="Wet cells" value={fmt(results.derived.wet_cells, 0)} />
            <ResultCard title="Inundated area" value={results.derived.flooded_area_km2 == null ? "—" : `${fmt(results.derived.flooded_area_km2, 3)} km²`} />
          </View>

          <TouchableOpacity style={styles.primaryButton} onPress={onMap}>
            <Ionicons name="map" size={18} color="#fff" />
            <Text style={styles.primaryButtonText}>OPEN FLOOD INUNDATION MAP</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.secondaryButton} onPress={onImpact}>
            <Ionicons name="warning-outline" size={18} color="#138A52" />
            <Text style={styles.secondaryText}>IMPACT ANALYSIS</Text>
          </TouchableOpacity>

          <View style={styles.notice}>
            <Ionicons name="information-circle-outline" size={20} color="#8A6410" />
            <Text style={styles.noticeText}>
              Output: 2D HLL screening scenario · GIS visualization
            </Text>
          </View>
        </>
      )}
    </ScrollView>
  );
}

function FloodMapScreen({ results, layer, setLayer, layerMeta, onBack, dam }: any) {
  const bounds = layerMeta?.bounds;
  const [animating, setAnimating] = useState(false);
  const [timeS, setTimeS] = useState(0);
  const [timelineMax, setTimelineMax] = useState(3600);

  useEffect(() => {
    fetch(`${API_BASE_URL}/api/flood/timeline`)
      .then(r => r.json())
      .then(d => { if (Number.isFinite(Number(d?.duration_s))) setTimelineMax(Number(d.duration_s)); })
      .catch(() => {});
  }, []);

  useEffect(() => {
    if (!animating) return;
    const id = setInterval(() => {
      setTimeS(t => {
        const next = t + 60;
        if (next >= timelineMax) { setAnimating(false); return timelineMax; }
        return next;
      });
    }, 350);
    return () => clearInterval(id);
  }, [animating, timelineMax]);

  const staticImageUri = layerMeta ? `${API_BASE_URL}${layerMeta.url}` : null;
  const imageUri = layer === "max-depth"
    ? `${API_BASE_URL}/api/flood/frame.png?time_s=${Math.round(timeS)}`
    : staticImageUri;

  return (
    <View style={{ flex: 1 }}>
      <View style={styles.mapTop}>
        <BackButton onPress={onBack} />
        <Text style={styles.mapTitle}>FLOOD INUNDATION MAP</Text>
        <Text style={styles.mapSub}>HLL screening GIS output · Mettur domain</Text>
      </View>

      <View style={styles.mapTabs}>
        {(["max-depth", "max-velocity", "arrival-time"] as LayerName[]).map((x) => (
          <TouchableOpacity
            key={x}
            style={[styles.mapTab, layer === x && styles.mapTabActive]}
            onPress={() => setLayer(x)}
          >
            <Text style={[styles.mapTabText, layer === x && styles.mapTabTextActive]}>
              {x === "max-depth" ? "DEPTH" : x === "max-velocity" ? "VELOCITY" : "ARRIVAL"}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      {layer === "max-depth" && (
        <View style={styles.animationBar}>
          <View style={{ flex: 1 }}>
            <Text style={styles.animationTitle}>2D FLOOD FLOW · {Math.round(timeS / 60)} min</Text>
            <Text style={styles.animationSub}>Green: low · Yellow: moderate · Red: extreme</Text>
          </View>
          <TouchableOpacity
            style={styles.playButton}
            onPress={() => { if (timeS >= timelineMax) setTimeS(0); setAnimating(v => !v); }}
          >
            <Ionicons name={animating ? "pause" : "play"} size={18} color="#fff" />
          </TouchableOpacity>
        </View>
      )}

      <MapView
        provider={PROVIDER_DEFAULT}
        style={{ flex: 1 }}
        initialRegion={
          bounds
            ? {
                latitude: (bounds[0][0] + bounds[1][0]) / 2,
                longitude: (bounds[0][1] + bounds[1][1]) / 2,
                latitudeDelta: Math.max(
                  Math.abs(bounds[1][0] - bounds[0][0]) * 1.25,
                  0.08
                ),
                longitudeDelta: Math.max(
                  Math.abs(bounds[1][1] - bounds[0][1]) * 1.25,
                  0.08
                ),
              }
            : {
                latitude: Number(dam?.latitude ?? DAM_COORD.latitude),
                longitude: Number(dam?.longitude ?? DAM_COORD.longitude),
                latitudeDelta: 0.25,
                longitudeDelta: 0.25,
              }
        }
      >
        <Marker
          coordinate={{
            latitude: Number(dam?.latitude ?? DAM_COORD.latitude),
            longitude: Number(dam?.longitude ?? DAM_COORD.longitude),
          }}
          title="Mettur Dam"
          description="Official government dam reference point"
        />
        {bounds && imageUri && (
          <Overlay
            key={`${layer}-${imageUri}`}
            image={{ uri: imageUri }}
            bounds={[
              [bounds[0][0], bounds[0][1]],
              [bounds[1][0], bounds[1][1]],
            ]}
            opacity={0.72}
          />
        )}
      </MapView>

      <View style={styles.mapLegend}>
        <Text style={styles.legendTitle}>
          {layer === "max-depth" ? "Maximum Depth" : layer === "max-velocity" ? "Maximum Velocity" : "Arrival Time"}
        </Text>
        <Text style={styles.legendValue}>
          {layerMeta ? `${fmt(layerMeta.min)} — ${fmt(layerMeta.max)}` : "Loading layer..."}
        </Text>
        <Text style={styles.legendNote}>
          Depth map is animated from the simulated arrival-time field. Risk colours are thresholded from model output.
        </Text>
      </View>
    </View>
  );
}

function ImpactScreen({ results, onBack }: any) {
  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <BackButton onPress={onBack} />
      <ScreenTitle title="IMPACT ANALYSIS" subtitle="Evidence-based inundation intelligence" />

      {results ? (
        <>
          <View style={styles.resultGrid}>
            <ResultCard title="Inundated area" value={results.derived.flooded_area_km2 == null ? "—" : `${fmt(results.derived.flooded_area_km2, 3)} km²`} />
            <ResultCard title="Maximum depth" value={`${fmt(results.derived.max_depth_m)} m`} />
          </View>

          <View style={styles.largeCard}>
            <Text style={styles.cardTitle}>Current impact layer</Text>
            <Text style={styles.bodyText}>
              The inundated area shown here is derived from the completed maximum-depth raster using the model's wet-cell threshold.
            </Text>
          </View>

          <View style={styles.largeCard}>
            <Text style={styles.cardTitle}>Affected assets</Text>
            <Text style={styles.bodyText}>
              Population, villages, roads, buildings and critical-service counts are not displayed yet because their GIS datasets have not been connected to this prototype.
            </Text>
            <View style={styles.pendingBox}>
              <Text style={styles.pendingText}>GIS ASSET LAYERS — PENDING REAL DATA</Text>
            </View>
          </View>
        </>
      ) : (
        <View style={styles.largeCard}>
          <Text style={styles.bodyText}>
            Run the completed HLL scenario first. NEERAKSH will not estimate impact values without an actual simulation output.
          </Text>
        </View>
      )}
    </ScrollView>
  );
}

function ComparisonScreen({ results, onBack }: any) {
  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <BackButton onPress={onBack} />
      <ScreenTitle title="MODEL COMPARISON" subtitle="Actual outputs only" />

      <CompareRow name="HLL" status={results ? "OUTPUT AVAILABLE" : "COMPLETED OUTPUT AVAILABLE"} active />
      <CompareRow name="SPH" status="NOT RUN" />
      <CompareRow name="Delft3D" status="NOT RUN" />

      <View style={styles.notice}>
        <Ionicons name="shield-checkmark-outline" size={20} color="#8A6410" />
        <Text style={styles.noticeText}>
          No comparison scores or accuracy numbers are shown until SPH and Delft3D are actually run and their outputs are available.
        </Text>
      </View>

      <View style={styles.largeCard}>
        <Text style={styles.cardTitle}>Planned comparison</Text>
        <Text style={styles.bodyText}>
          Flood extent · maximum depth · arrival time · velocity · conservation / numerical behaviour.
        </Text>
      </View>
    </ScrollView>
  );
}

function ExportScreen({ onBack }: { onBack: () => void }) {
  const files = [
    "mettur_max_depth.tif",
    "mettur_final_depth.tif",
    "mettur_max_velocity.tif",
    "mettur_arrival_time.tif",
    "mettur_hll_timeseries.csv",
    "mettur_hll_results_summary.json",
  ];

  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <BackButton onPress={onBack} />
      <ScreenTitle title="EXPORT FILES" subtitle="GIS-ready outputs generated by NEERAKSH" />

      <View style={styles.largeCard}>
        {files.map((file) => (
          <View style={styles.fileRow} key={file}>
            <Ionicons name="document-outline" size={20} color="#138A52" />
            <Text style={styles.fileName}>{file}</Text>
            <Ionicons name="checkmark-circle" size={18} color="#138A52" />
          </View>
        ))}
      </View>

      <View style={styles.notice}>
        <Ionicons name="information-circle-outline" size={20} color="#8A6410" />
        <Text style={styles.noticeText}>
          The files are already generated by the Mettur HLL run. SHP/KML conversion will be added after the GIS export module is connected.
        </Text>
      </View>
    </ScrollView>
  );
}

function SectionTitle({ title }: { title: string }) {
  return <Text style={styles.sectionTitle}>{title}</Text>;
}

function ScreenTitle({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <View style={{ marginBottom: 14 }}>
      <Text style={styles.screenTitle}>{title}</Text>
      <Text style={styles.screenSubtitle}>{subtitle}</Text>
    </View>
  );
}

function BackButton({ onPress }: { onPress: () => void }) {
  return (
    <TouchableOpacity style={styles.back} onPress={onPress}>
      <Ionicons name="arrow-back" size={18} color="#138A52" />
      <Text style={styles.backText}>Back</Text>
    </TouchableOpacity>
  );
}

function WorkflowButton({ icon, title, onPress }: any) {
  return (
    <TouchableOpacity style={styles.workflowButton} onPress={onPress}>
      <Ionicons name={icon} size={23} color="#138A52" />
      <Text style={styles.workflowText}>{title}</Text>
    </TouchableOpacity>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.metric}>
      <Text style={styles.metricLabel}>{label}</Text>
      <Text style={styles.metricValue}>{value}</Text>
    </View>
  );
}

function ResultCard({ title, value }: { title: string; value: string }) {
  return (
    <View style={styles.resultCard}>
      <Text style={styles.resultLabel}>{title}</Text>
      <Text style={styles.resultValue}>{value}</Text>
    </View>
  );
}

function StatusRow({ label, value, good = false }: { label: string; value: string; good?: boolean }) {
  return (
    <View style={styles.statusRow}>
      <Text style={styles.statusLabel}>{label}</Text>
      <Text style={[styles.statusValue, good ? styles.good : styles.pending]}>{value}</Text>
    </View>
  );
}

function CompareRow({ name, status, active = false }: { name: string; status: string; active?: boolean }) {
  return (
    <View style={styles.compareRow}>
      <View style={styles.compareName}>
        <Ionicons name={active ? "checkmark-circle" : "ellipse-outline"} size={22} color={active ? "#138A52" : "#9A7A2A"} />
        <Text style={styles.cardTitle}>{name}</Text>
      </View>
      <Text style={[styles.statusValue, active ? styles.good : styles.pending]}>{status}</Text>
    </View>
  );
}

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F7F8F5" },
  header: {
    height: 64,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E1E8E2",
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerIcon: { width: 38, alignItems: "center" },
  headerBrand: { color: "#164B2A", fontWeight: "900", letterSpacing: 2.5, fontSize: 20 },
  headerSub: { color: "#718277", fontSize: 10, marginTop: 1 },
  headerStatus: { marginLeft: "auto", flexDirection: "row", alignItems: "center", gap: 5, borderWidth: 1, borderColor: "#B8CDBD", borderRadius: 5, paddingHorizontal: 7, paddingVertical: 5 },
  headerStatusText: { color: "#41614D", fontSize: 9, fontWeight: "800" },
  statusDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#138A52" },

  login: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28 },
  logoCircle: { width: 92, height: 92, borderRadius: 46, backgroundColor: "#138A52", alignItems: "center", justifyContent: "center", marginBottom: 16 },
  logoText: { color: "#164B2A", fontWeight: "900", letterSpacing: 4, fontSize: 31 },
  loginTitle: { color: "#334D60", fontWeight: "700", fontSize: 15, textAlign: "center", marginTop: 7 },
  loginText: { color: "#75828C", textAlign: "center", fontSize: 12, lineHeight: 19, marginTop: 12, maxWidth: 330 },
  apiWarning: { backgroundColor: "#FFF7E1", borderWidth: 1, borderColor: "#E7C66E", padding: 10, borderRadius: 7, marginTop: 18, width: "100%" },
  apiWarningText: { color: "#775B12", fontSize: 11, textAlign: "center" },
  primaryButton: { marginTop: 18, minHeight: 48, backgroundColor: "#138A52", borderRadius: 7, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 },
  primaryButtonText: { color: "#FFFFFF", fontWeight: "800", fontSize: 12, letterSpacing: .4 },
  sourceNote: { color: "#89949D", fontSize: 10, textAlign: "center", marginTop: 14 },

  scroll: { padding: 16, paddingBottom: 30 },
  hero: { backgroundColor: "#164B2A", borderRadius: 10, padding: 19, marginBottom: 18 },
  eyebrow: { color: "#F0B323", fontWeight: "800", fontSize: 9, letterSpacing: 1.1 },
  heroTitle: { color: "#fff", fontWeight: "900", fontSize: 24, marginTop: 7 },
  heroText: { color: "#E6F1E9", fontSize: 12, lineHeight: 18, marginTop: 7 },
  sectionTitle: { color: "#176B3A", fontWeight: "900", fontSize: 11, letterSpacing: 1.1, marginTop: 2, marginBottom: 9 },
  damCard: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#DCE6DE", borderRadius: 8, padding: 13, flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 18 },
  damIcon: { width: 47, height: 47, backgroundColor: "#E7F4EC", borderRadius: 8, alignItems: "center", justifyContent: "center" },
  cardTitle: { color: "#294A36", fontWeight: "800", fontSize: 14 },
  cardSub: { color: "#718076", fontSize: 11, marginTop: 3 },
  workflowGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginBottom: 18 },
  workflowButton: { width: (width - 41) / 2, minHeight: 74, backgroundColor: "#fff", borderWidth: 1, borderColor: "#DCE6DE", borderRadius: 8, padding: 11, justifyContent: "center", gap: 5 },
  workflowText: { color: "#3F5D49", fontWeight: "700", fontSize: 11 },
  statusCard: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#DCE6DE", borderRadius: 8, paddingHorizontal: 13, marginBottom: 12 },
  statusRow: { minHeight: 41, borderBottomWidth: 1, borderBottomColor: "#EEF1F3", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  statusLabel: { color: "#53646F", fontSize: 11 },
  statusValue: { fontSize: 9, fontWeight: "900" },
  good: { color: "#138A52" },
  pending: { color: "#967223" },
  notice: { backgroundColor: "#FFF8E8", borderWidth: 1, borderColor: "#E5C96F", borderRadius: 7, padding: 10, flexDirection: "row", gap: 8, alignItems: "flex-start", marginTop: 10 },
  noticeText: { flex: 1, color: "#6B551B", fontSize: 10.5, lineHeight: 16 },

  back: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 10 },
  backText: { color: "#138A52", fontWeight: "700", fontSize: 12 },
  screenTitle: { color: "#164B2A", fontSize: 22, fontWeight: "900" },
  screenSubtitle: { color: "#7B8993", fontSize: 11, marginTop: 3 },
  largeCard: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#DCE6DE", borderRadius: 8, padding: 14, marginBottom: 12 },
  bigTitle: { color: "#164B2A", fontSize: 20, fontWeight: "900" },
  bodyText: { color: "#5E6D77", fontSize: 12, lineHeight: 19, marginTop: 7 },
  mapMini: { height: 145, borderRadius: 7, overflow: "hidden", marginTop: 13, marginBottom: 12 },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  metric: { backgroundColor: "#F4F7F3", borderRadius: 6, padding: 9, width: (width - 55) / 2 },
  metricLabel: { color: "#758078", fontSize: 9, textTransform: "uppercase" },
  metricValue: { color: "#315640", fontWeight: "800", fontSize: 14, marginTop: 3 },
  liveBadge: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "#E8F5ED", borderRadius: 4, paddingHorizontal: 7, paddingVertical: 5 },
  liveBadgeText: { color: "#197344", fontWeight: "900", fontSize: 9 },
  timestamp: { color: "#89959D", fontSize: 9, marginTop: 9 },
  sourceNoteSmall: { color: "#8A969E", fontSize: 9, marginTop: 4 },
  pickerWrap: { borderWidth: 1, borderColor: "#D5DEE4", borderRadius: 6, marginTop: 7, overflow: "hidden" },
  label: { color: "#61717C", fontSize: 10, fontWeight: "700", textTransform: "uppercase" },
  disabledButton: { backgroundColor: "#9AA39C" },

  resultBanner: { backgroundColor: "#EAF7F0", borderWidth: 1, borderColor: "#B9DDC8", borderRadius: 8, padding: 13, flexDirection: "row", gap: 10, alignItems: "center", marginBottom: 12 },
  resultCheck: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#138A52", alignItems: "center", justifyContent: "center" },
  resultGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginBottom: 12 },
  resultCard: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#DCE6DE", borderRadius: 8, padding: 13, width: (width - 41) / 2 },
  resultLabel: { color: "#7A8790", fontSize: 10 },
  resultValue: { color: "#164B2A", fontSize: 19, fontWeight: "900", marginTop: 5 },
  twoButtons: { flexDirection: "row", gap: 9 },
  secondaryButton: { flex: 1, minHeight: 45, borderWidth: 1, borderColor: "#9DBDA8", borderRadius: 7, backgroundColor: "#fff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  secondaryText: { color: "#138A52", fontSize: 10, fontWeight: "900" },

  animationBar: { backgroundColor: "#164B2A", paddingHorizontal: 12, paddingVertical: 9, flexDirection: "row", alignItems: "center", gap: 10 },
  animationTitle: { color: "#FFFFFF", fontSize: 10, fontWeight: "900", letterSpacing: .5 },
  animationSub: { color: "#DDEBE1", fontSize: 9, marginTop: 2 },
  playButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#F0B323", alignItems: "center", justifyContent: "center" },
  mapTop: { backgroundColor: "#fff", padding: 11, borderBottomWidth: 1, borderBottomColor: "#DCE6DE" },
  mapTitle: { color: "#164B2A", fontSize: 18, fontWeight: "900" },
  mapSub: { color: "#7B8993", fontSize: 10, marginTop: 2 },
  mapTabs: { backgroundColor: "#fff", flexDirection: "row", padding: 8, gap: 6, borderBottomWidth: 1, borderBottomColor: "#E1E6EA" },
  mapTab: { flex: 1, paddingVertical: 8, alignItems: "center", borderWidth: 1, borderColor: "#D5DEE4", borderRadius: 5 },
  mapTabActive: { backgroundColor: "#E9F3F8", borderColor: "#80AFC5" },
  mapTabText: { color: "#657580", fontSize: 9, fontWeight: "800" },
  mapTabTextActive: { color: "#138A52" },
  mapLegend: { position: "absolute", left: 13, right: 13, bottom: 14, backgroundColor: "rgba(255,255,255,.95)", borderRadius: 7, borderWidth: 1, borderColor: "#DCE6DE", padding: 10 },
  legendTitle: { color: "#164B2A", fontWeight: "900", fontSize: 12 },
  legendValue: { color: "#138A52", fontWeight: "800", fontSize: 11, marginTop: 3 },
  legendNote: { color: "#788690", fontSize: 9, marginTop: 3 },

  compareRow: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#DCE6DE", borderRadius: 8, minHeight: 56, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 9 },
  compareName: { flexDirection: "row", alignItems: "center", gap: 8 },
  pendingBox: { backgroundColor: "#F7F2E6", borderRadius: 5, padding: 9, marginTop: 10 },
  pendingText: { color: "#7B5D1A", fontSize: 10, fontWeight: "800" },
  fileRow: { minHeight: 46, borderBottomWidth: 1, borderBottomColor: "#EEF1F3", flexDirection: "row", alignItems: "center", gap: 9 },
  fileName: { flex: 1, color: "#4B5D68", fontSize: 11 },
});
